#!/bin/bash
# woland install script 1.01

# WOLAND PREREQUISITES
# The following software must be present before installing Woland.
# PERL
# Perl is required to run Woland. Minimal recommended Perl version is 5.17.
# To check Perl version type:
# $ perl -v 
#
# R
# You also need R in order to generate reports.
# Minimal recommended R version is 3.1.

#  test if there is an argument 

# if [ "$#" != "1" ]; then
#     echo " "
#     echo "INSTALL"
#     echo "    purpose:  install woland 1.01"
#     echo "    WARNING:  you should first git clone woland or untar woland source files. "
#     echo "    usage:    ./INSTALL [woland directory]"
#     echo "    example:  ./INSTALL /home/user/tools/woland/"
#     echo " "
#     exit 1
# fi

# convert relative path to absolute path

echo -n "SETTING PATH: $PREFIX... "

ABSPATH=`cd $1; pwd`
ABSPATH="$ABSPATH/"
echo "path is now: $ABSPATH"
if [ -e "Makefile.local" ];
  then LATERRUN="1";
fi 

# installing cpanm & modules

echo -n "INSTALLING cpanminus module... "
perl -MCPAN -Mlocal::lib -e 'App:cpanminus'
echo -n "INSTALLING Bio::DB::Fasta... "
cpanm Bio::DB::Fasta
echo -n "INSTALLING Cwd... "
cpanm Cwd
echo -n "INSTALLING List::Util... "
cpanm List::Util
echo -n "INSTALLING IPC::System::Simple... "
cpanm IPC::System::Simple
echo -n "INSTALLING IPC::Run... "
cpanm IPC::Run
echo -n "INSTALLING Parallel::ForkManager... "
cpanm Parallel::ForkManager
echo -n "INSTALLING Regexp::Common... "
cpanm Regexp::Common
echo -n "INSTALLING Text::Balanced... "
cpanm Text::Balanced
echo -n "INSTALLING Text::Wrap... "
cpanm Text::Wrap
echo -n "INSTALLING Statistics::R... "
cpanm Statistics::R

# installing R & libraries
echo -n "INSTALLING R Packages... "
Rscript $ABSPATH INSTALL.R

echo "DONE"

exit 0